version: '3.1'

services:

  db:
    image: postgres:9.6.17-alpine 
    restart: always
    environment:
      POSTGRES_PASSWORD: employer
      POSTGRES_USER : employer
    ports:
      - 5432:5432

