version: '3.1'

services:

  db:
    image: postgres:9.6.17-alpine 
    restart: always
    environment:
      POSTGRES_PASSWORD: pgadmin999 
      POSTGRES_USER : root
    volumes:
       - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
      
